### ISSUE TITLE
$max_trials equals NaN

### ISSUE THREAD

**Issue by jzureich** [Nmoleo64/MeliorationWeb2#6]
The maximum number of trials is loading in as NaN (e.g. 5/NaN) and, thus, the Practice Period never ends. The problem seems to be that $max_trials is not loading from the config file (I actually could not find the config file anywhere in the code files).

**Comment by Nmoleo64** [comment]
Good catch! We deleted the config file and moved it to the database, but I must have forgotten to make $max_trials be set to the value from the database; it's still looking for something from the config.

**Comment by Nmoleo64** [comment]
Fixed
