### ISSUE TITLE
Omit option to manually enter workerId (ONCE WE GO LIVE)

### ISSUE THREAD

**Issue by jzureich** [Nmoleo64/MeliorationWeb2#7]
We do not want to let them enter a different WorkerID. Forcing this to auto-populate from MTurk is an important part of our safeguard against multiple attempts.

**Comment by Nmoleo64** [comment]
Ok, I can do this. I will start making a new start page that doesn't let you type in a MTurkID.

**Comment by Nmoleo64** [comment]
I am closing this for now, it is on my to-do list under finishing touches.
